name: Publish Docker image

on:
  release:
    types: [published]

jobs:
<<<<<<< HEAD

  build:
    environment: production
=======
  push_to_registries:
    environment: production
    name: Push Docker image
>>>>>>> dev
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
<<<<<<< HEAD
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag danielmcdonough/docker-static-website:{{ github.sha }}
    - name: Login to Dockerhub
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v4.1.1
      with:
        context: "${{ github.workspace }}"
        push: true
        tags: danielmcdonough/docker-static-website:{{ github.sha }}
=======
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@2.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@4.6.0
        with:
          images: |
            danielmcdonough/docker-static-website
      
      - name: Build and push Docker images
        uses: docker/build-push-action@4.1.1
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
>>>>>>> dev
