name: Docker Image CI

on:
  release:
    types: [published]

jobs:

  build:
    environment: production
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag danielmcdonough/docker-static-website:{{ github.sha }}
    - name: Login to Dockerhub
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v4.1.1
      with:
        context: "${{ github.workspace }}"
        push: true
        tags: danielmcdonough/docker-static-website:{{ github.sha }}
